FROM influxdb:3.3-core

# Using root user for dev to avoid volume permission issues
USER 0:0

COPY ./lib/argparser.sh /script/argparser.sh
RUN chmod +x /script/argparser.sh

COPY ./lib/waitnet.sh /script/waitnet.sh
RUN chmod +x /script/waitnet.sh

COPY ./influxdb/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV SCRIPT_WAITNET_PATH=/script/waitnet.sh
ENV SCRIPT_ARGPARSER_PATH=/script/argparser.sh

ENTRYPOINT ["/entrypoint.sh"]
