events {}

http {
   upstream grpc_backend {
      server ingestion-api:50051;
   }

   server {
      listen 443 ssl;
      http2 on;  

      ssl_certificate     /etc/nginx/certs/server.crt;
      ssl_certificate_key /etc/nginx/certs/server.key;

      ssl_client_certificate /etc/nginx/certs/ca.crt;
      ssl_verify_client on;  # force client certificate verification

      # Max idle time for an open HTTP/2 stream (no frames received)
      client_body_timeout 90s;

      location / {
         grpc_pass grpc://grpc_backend;

         # Max time to wait for a complete response from upstream gRPC
         grpc_read_timeout 30s;
         # Max time to wait when sending request data to upstream gRPC
         grpc_send_timeout 30s;

         grpc_set_header x-client-dn $ssl_client_s_dn;
         grpc_set_header x-forwarded-for $remote_addr;
      }
   }
}