FROM golang:1.24.5-alpine 

WORKDIR /src

RUN apk --no-cache add curl bash

COPY ./run.dev.sh /run.dev.sh
RUN chmod +x /run.dev.sh

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.0/migrate.linux-amd64.tar.gz | tar xvz \
   && mv migrate $GOPATH/bin/migrate 

ENTRYPOINT ["/run.dev.sh"]