services:
  postgres:
    image: postgres:17.6
    container_name: sensorflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: S3ns0rF!0w#2025
      POSTGRES_DB: sensorflow
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sensorflow-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./grpc-reverse-proxy
      dockerfile: Dockerfile.dev
    image: sensorflow/grpc-reverse-proxy:dev
    pull_policy: never
    container_name: sensorflow-grpc-reverse-proxy
    volumes:
      - ./grpc-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - certs_data:/etc/nginx/certs
    ports:
      - 443:443
    depends_on:
      - ingestion-api
    networks:
      - sensorflow-net

  cli:
    build:
      context: .
      dockerfile: Dockerfile.gowaitfile.dev
    image: sensorflow/gowaitfile:dev
    pull_policy: never
    container_name: sensorflow-cli
    working_dir: /src
    environment:
      GO_SOURCE_FILE: /src/cmd/cli/main.go
      GO_BIN_PATH: /usr/local/bin/cli
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
      DATABASE_URL: 'postgres://root:S3ns0rF%210w%232025@postgres/sensorflow?sslmode=disable'
    volumes:
      - ../back:/src
      - shared:/shared/influx:ro
    env_file:
      - ./cli/.env.dev
    networks:
      - sensorflow-net
    command: [ 
      "--file", "/shared/influx/admin.token",
      "--cmd", "export INFLUXDB_TOKEN=$(cat /shared/influx/admin.token)",
    ]

  ingestion-api:
    build:
      context: .
      dockerfile: Dockerfile.gowaitfile.dev
    image: sensorflow/gowaitfile:dev
    pull_policy: never
    container_name: sensorflow-ingestion-api
    working_dir: /src
    ports:
      - 50051:50051
    environment:
      GO_SOURCE_FILE: /src/cmd/ingestion/main.go
      GO_BIN_PATH: /usr/local/bin/ingestion
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
    volumes:
      - ../back:/src
      - shared:/shared/influx:ro
    env_file:
      - ./ingestion/.env.dev
    networks:
      - sensorflow-net
    depends_on:
      - influxdb
    command: [ 
      "--file", "/shared/influx/admin.token",
      "--cmd", "export INFLUXDB_TOKEN=$(cat /shared/influx/admin.token)",
    ]

  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile.gowaitfile.dev
    image: sensorflow/gowaitfile:dev
    pull_policy: never
    container_name: sensorflow-gateway-api
    working_dir: /src
    ports:
      - 8000:8000
    environment:
      GO_SOURCE_FILE: /src/cmd/gateway/main.go
      GO_BIN_PATH: /usr/local/bin/gateway
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
    volumes:
      - ../back:/src
      - shared:/shared/influx:ro
    env_file:
      - ./gateway/.env.dev
    networks:
      - sensorflow-net
    depends_on:
      - influxdb
    command: [ 
      "--file", "/shared/influx/admin.token",
      "--cmd", "export INFLUXDB_TOKEN=$(cat /shared/influx/admin.token)",
    ]
    
  kafka:
    image: apache/kafka:4.0.0
    container_name: sensorflow-kafka
    ports:
      - 9092:9092 # Gateway
      - 9093:9093 # KRaft internal quorum (cluster usage)
    volumes:
      - kafkadata:/var/lib/kafka/data
    env_file:
      - ./kafka/.env.dev
    networks:
      - sensorflow-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: sensorflow-kafka-ui
    ports:
      - 8001:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - sensorflow-net
    depends_on:
      - kafka

  influxdb:
    build:
      context: .
      dockerfile: influxdb/Dockerfile.dev
    image: sensorflow/influxdb:dev
    pull_policy: never
    container_name: sensorflow-influxdb3-core
    platform: linux/amd64
    ports:
      - 8181:8181 # Gateway gRPC/HTTP/SQL
    volumes:
      - influxdata:/var/lib/influxdb
      - shared:/shared/influx:rw
    env_file:
      - ./influxdb/.env.dev
    networks:
      - sensorflow-net
    command: [ "--token-path", "/shared/influx/admin.token" ]

  influxdb-ui:
    build:
      context: .
      dockerfile: influxdb/Dockerfile.ui.dev
    image: sensorflow/influxdb-ui:dev
    pull_policy: never
    container_name: sensorflow-influxdb3-ui
    platform: linux/amd64
    ports:
      - 8002:80
    volumes:
      - shared:/shared/influx:ro
    networks:
      - sensorflow-net
    depends_on:
      - influxdb
    command: [
      "--token-path", "/shared/influx/admin.token",
      "--db-name", "measurements",
      "--influx-addr", "http://influxdb:8181"
    ]
  
networks:
  sensorflow-net:
    driver: bridge

volumes:
  shared:
  pgdata:
  kafkadata:
  influxdata:
  certs_data:
    driver: local
    driver_opts:
      type: none
      device: ./certs
      o: bind
  client_certs_data:
    driver: local
    driver_opts:
      type: none
      device: ./client_certs
      o: bind
