services:
  ingestion-api:
    image: golang:1.24.5
    container_name: sensorflow-ingestion-api
    working_dir: /src
    environment:
      GO_SOURCE_FILE: /src/cmd/ingestion/main.go
      GO_BIN_PATH: /usr/local/bin/ingestion
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
    volumes:
      - ../back:/src
      - shared:/shared/influx:ro
      - ./run.dev.sh:/run.dev.sh:ro
      - ./lib/waitfile.sh:/waitfile.sh:ro
    env_file:
      - ./ingestion/.env.dev
    networks:
      - sensorflow-net
    depends_on:
      - influxdb
    entrypoint: [ 
      "bash", "/waitfile.sh", 
      "--file", "/shared/influx/admin.token",
      "--cmd", "export INFLUXDB_TOKEN=$(cat /shared/influx/admin.token)",
      "--exec", "/run.dev.sh"
    ]

  gateway-api:
    image: golang:1.24.5
    container_name: sensorflow-gateway-api
    working_dir: /src
    ports:
      - 8000:8000
    environment:
      GO_SOURCE_FILE: /src/cmd/gateway/main.go
      GO_BIN_PATH: /usr/local/bin/gateway
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
    volumes:
      - ../back:/src
      - shared:/shared/influx:ro
      - ./run.dev.sh:/run.dev.sh:ro
      - ./lib/waitfile.sh:/waitfile.sh:ro
    env_file:
      - ./gateway/.env.dev
    networks:
      - sensorflow-net
    depends_on:
      - influxdb
    entrypoint: [ 
      "bash", "/waitfile.sh", 
      "--file", "/shared/influx/admin.token",
      "--cmd", "export INFLUXDB_TOKEN=$(cat /shared/influx/admin.token)",
      "--exec", "/run.dev.sh"
    ]
    
  kafka:
    image: apache/kafka:4.0.0
    container_name: sensorflow-kafka
    ports:
      - 9092:9092 # Gateway
      - 9093:9093 # KRaft internal quorum (cluster usage)
    volumes:
      - kafka_volume:/var/lib/kafka/data
    env_file:
      - ./kafka/.env.dev
    networks:
      - sensorflow-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: sensorflow-kafka-ui
    ports:
      - 8001:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - sensorflow-net
    depends_on:
      - kafka

  influxdb:
    image: influxdb:3.3-core
    container_name: sensorflow-influxdb3-core
    platform: linux/amd64
    user: 0:0 # Using root user for dev to avoid volume permission issues
    ports:
      - 8181:8181 # Gateway gRPC/HTTP/SQL
    volumes:
      - influxdb_data:/var/lib/influxdb
      - shared:/shared/influx:rw
      - ./influxdb/entrypoint.sh:/entrypoint.sh:ro
      - ./lib/argparser.sh:/script/argparser.sh:ro
      - ./lib/waitnet.sh:/script/waitnet.sh:ro
    env_file:
      - ./influxdb/.env.dev
    environment:
      SCRIPT_WAITNET_PATH: /script/waitnet.sh
      SCRIPT_ARGPARSER_PATH: /script/argparser.sh
    networks:
      - sensorflow-net
    entrypoint: [ "/entrypoint.sh", "--token-path", "/shared/influx/admin.token" ]

  influxdb-ui:
    image: influxdata/influxdb3-ui:1.1.0
    container_name: sensorflow-influxdb3-ui
    platform: linux/amd64
    ports:
      - 8002:80
    volumes:
      - shared:/shared/influx:ro
      - ./lib/argparser.sh:/argparser.sh:ro
      - ./lib/waitfile.sh:/waitfile.sh:ro
      - ./influxdb/entrypoint-ui.sh:/init.sh:ro
    entrypoint: [
      "sh", "/init.sh", 
      "--token-path", "/shared/influx/admin.token",
      "--db-name", "measurements",
      "--influx-addr", "http://influxdb:8181"
    ]
    networks:
      - sensorflow-net
    depends_on:
      - influxdb
  
networks:
  sensorflow-net:
    driver: bridge

volumes:
  kafka_volume:
  influxdb_data:
  shared:
