services:
  postgres:
    image: postgres:17.6
    container_name: sensorflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: S3ns0rF!0w#2025
      POSTGRES_DB: sensorflow
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sensorflow-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d sensorflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2.3
    container_name: sensorflow-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - sensorflow-net
    command: ["redis-server", "--appendonly", "yes"]
    
  nginx:
    build:
      context: ./grpc-reverse-proxy
      dockerfile: Dockerfile.dev
    image: sensorflow/grpc-reverse-proxy:dev
    pull_policy: never
    container_name: sensorflow-grpc-reverse-proxy
    volumes:
      - ./grpc-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - certs_data:/etc/nginx/certs
    ports:
      - 443:443
    depends_on:
      - ingestion-api
    networks:
      - sensorflow-net

  cli:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sensorflow/goback:dev
    pull_policy: never
    container_name: sensorflow-cli
    working_dir: /src
    environment:
      GO_SOURCE_FILE: /src/cmd/cli/main.go
      GO_BIN_PATH: /usr/local/bin/cli
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
      PG_DATABASE_URL: 'postgres://root:S3ns0rF%210w%232025@postgres/sensorflow?sslmode=disable'
      CLICKHOUSE_DATABASE_URL: 'clickhouse://default:@clickhouse:9000/default'
      CLIENT_CERTS_DIR: /client_certs
    volumes:
      - ../back:/src
      - client_certs_data:/client_certs
    env_file:
      - ./cli/.env.dev
    networks:
      - sensorflow-net

  ingestion-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sensorflow/goback:dev
    pull_policy: never
    container_name: sensorflow-ingestion-api
    working_dir: /src
    ports:
      - 50051:50051
    environment:
      GO_SOURCE_FILE: /src/cmd/ingestion/main.go
      GO_BIN_PATH: /usr/local/bin/ingestion
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
    volumes:
      - ../back:/src
    env_file:
      - ./ingestion/.env.dev
    networks:
      - sensorflow-net
    depends_on:
      - clickhouse
      - postgres
      - redis

  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sensorflow/goback:dev
    pull_policy: never
    container_name: sensorflow-gateway-api
    working_dir: /src
    ports:
      - 8000:8000
    environment:
      GO_SOURCE_FILE: /src/cmd/gateway/main.go
      GO_BIN_PATH: /usr/local/bin/gateway
      GO_BUILD_FLAGS: -buildvcs=false -gcflags="all=-N -l"
    volumes:
      - ../back:/src
    env_file:
      - ./gateway/.env.dev
    networks:
      - sensorflow-net
    depends_on:
      - postgres
      - redis
    
  kafka:
    image: apache/kafka:4.0.0
    container_name: sensorflow-kafka
    ports:
      - 9092:9092 # Gateway
      - 9093:9093 # KRaft internal quorum (cluster usage)
    volumes:
      - kafkadata:/var/lib/kafka/data
    env_file:
      - ./kafka/.env.dev
    networks:
      - sensorflow-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: sensorflow-kafka-ui
    ports:
      - 8001:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - sensorflow-net
    depends_on:
      - kafka
  
  clickhouse:
    image: clickhouse/clickhouse-server:25.9.6
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - 8123:8123   # HTTP API
      - 9000:9000   # Native TCP interface
      - 9009:9009   # Interserver (cluster usage)
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_cold:/var/lib/clickhouse/cold_data
      - clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse/docker.xml:/etc/clickhouse-server/config.d/docker.xml:ro
      - ./clickhouse/init-cold-data.sh:/etc/clickhouse/init-cold-data.sh:ro
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    entrypoint: ["/bin/bash", "/etc/clickhouse/init-cold-data.sh"]
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    networks:
      - sensorflow-net
  
networks:
  sensorflow-net:
    driver: bridge

volumes:
  clickhouse_data:
  clickhouse_cold:
  clickhouse_logs:
  pgdata:
  redisdata:
  kafkadata:
  certs_data:
    driver: local
    driver_opts:
      type: none
      device: ./certs
      o: bind
  client_certs_data:
    driver: local
    driver_opts:
      type: none
      device: ./client_certs
      o: bind
