FROM golang:1.24.5 

WORKDIR /src

COPY ./lib/waitfile.sh /waitfile.sh
RUN chmod +x /waitfile.sh

COPY ./run.dev.sh /run.dev.sh
RUN chmod +x /run.dev.sh

# Entrypoint automatically executed /run.dev.sh and leaves the --file and --cmd parameters flexible
ENTRYPOINT ["/waitfile.sh", "--exec", "/run.dev.sh"]