// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: back/internal/adapters/grpc/proto/sensor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorService_StreamCustomMeasurements_FullMethodName    = "/sensor.SensorService/StreamCustomMeasurements"
	SensorService_UnaryCustomMeasurements_FullMethodName     = "/sensor.SensorService/UnaryCustomMeasurements"
	SensorService_StreamAccelGyroMeasurements_FullMethodName = "/sensor.SensorService/StreamAccelGyroMeasurements"
	SensorService_UnaryAccelGyroMeasurements_FullMethodName  = "/sensor.SensorService/UnaryAccelGyroMeasurements"
)

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorServiceClient interface {
	StreamCustomMeasurements(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CustomMeasurementsRequest, IngestAck], error)
	UnaryCustomMeasurements(ctx context.Context, in *CustomMeasurementsRequest, opts ...grpc.CallOption) (*IngestAck, error)
	StreamAccelGyroMeasurements(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AccelGyroMeasurementsRequest, IngestAck], error)
	UnaryAccelGyroMeasurements(ctx context.Context, in *AccelGyroMeasurementsRequest, opts ...grpc.CallOption) (*IngestAck, error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) StreamCustomMeasurements(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CustomMeasurementsRequest, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[0], SensorService_StreamCustomMeasurements_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CustomMeasurementsRequest, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_StreamCustomMeasurementsClient = grpc.BidiStreamingClient[CustomMeasurementsRequest, IngestAck]

func (c *sensorServiceClient) UnaryCustomMeasurements(ctx context.Context, in *CustomMeasurementsRequest, opts ...grpc.CallOption) (*IngestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAck)
	err := c.cc.Invoke(ctx, SensorService_UnaryCustomMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) StreamAccelGyroMeasurements(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AccelGyroMeasurementsRequest, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[1], SensorService_StreamAccelGyroMeasurements_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AccelGyroMeasurementsRequest, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_StreamAccelGyroMeasurementsClient = grpc.BidiStreamingClient[AccelGyroMeasurementsRequest, IngestAck]

func (c *sensorServiceClient) UnaryAccelGyroMeasurements(ctx context.Context, in *AccelGyroMeasurementsRequest, opts ...grpc.CallOption) (*IngestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAck)
	err := c.cc.Invoke(ctx, SensorService_UnaryAccelGyroMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServiceServer is the server API for SensorService service.
// All implementations must embed UnimplementedSensorServiceServer
// for forward compatibility.
type SensorServiceServer interface {
	StreamCustomMeasurements(grpc.BidiStreamingServer[CustomMeasurementsRequest, IngestAck]) error
	UnaryCustomMeasurements(context.Context, *CustomMeasurementsRequest) (*IngestAck, error)
	StreamAccelGyroMeasurements(grpc.BidiStreamingServer[AccelGyroMeasurementsRequest, IngestAck]) error
	UnaryAccelGyroMeasurements(context.Context, *AccelGyroMeasurementsRequest) (*IngestAck, error)
	mustEmbedUnimplementedSensorServiceServer()
}

// UnimplementedSensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorServiceServer struct{}

func (UnimplementedSensorServiceServer) StreamCustomMeasurements(grpc.BidiStreamingServer[CustomMeasurementsRequest, IngestAck]) error {
	return status.Error(codes.Unimplemented, "method StreamCustomMeasurements not implemented")
}
func (UnimplementedSensorServiceServer) UnaryCustomMeasurements(context.Context, *CustomMeasurementsRequest) (*IngestAck, error) {
	return nil, status.Error(codes.Unimplemented, "method UnaryCustomMeasurements not implemented")
}
func (UnimplementedSensorServiceServer) StreamAccelGyroMeasurements(grpc.BidiStreamingServer[AccelGyroMeasurementsRequest, IngestAck]) error {
	return status.Error(codes.Unimplemented, "method StreamAccelGyroMeasurements not implemented")
}
func (UnimplementedSensorServiceServer) UnaryAccelGyroMeasurements(context.Context, *AccelGyroMeasurementsRequest) (*IngestAck, error) {
	return nil, status.Error(codes.Unimplemented, "method UnaryAccelGyroMeasurements not implemented")
}
func (UnimplementedSensorServiceServer) mustEmbedUnimplementedSensorServiceServer() {}
func (UnimplementedSensorServiceServer) testEmbeddedByValue()                       {}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	// If the following call panics, it indicates UnimplementedSensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_StreamCustomMeasurements_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServiceServer).StreamCustomMeasurements(&grpc.GenericServerStream[CustomMeasurementsRequest, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_StreamCustomMeasurementsServer = grpc.BidiStreamingServer[CustomMeasurementsRequest, IngestAck]

func _SensorService_UnaryCustomMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomMeasurementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).UnaryCustomMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_UnaryCustomMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).UnaryCustomMeasurements(ctx, req.(*CustomMeasurementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_StreamAccelGyroMeasurements_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServiceServer).StreamAccelGyroMeasurements(&grpc.GenericServerStream[AccelGyroMeasurementsRequest, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_StreamAccelGyroMeasurementsServer = grpc.BidiStreamingServer[AccelGyroMeasurementsRequest, IngestAck]

func _SensorService_UnaryAccelGyroMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccelGyroMeasurementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).UnaryAccelGyroMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_UnaryAccelGyroMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).UnaryAccelGyroMeasurements(ctx, req.(*AccelGyroMeasurementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sensor.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryCustomMeasurements",
			Handler:    _SensorService_UnaryCustomMeasurements_Handler,
		},
		{
			MethodName: "UnaryAccelGyroMeasurements",
			Handler:    _SensorService_UnaryAccelGyroMeasurements_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCustomMeasurements",
			Handler:       _SensorService_StreamCustomMeasurements_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAccelGyroMeasurements",
			Handler:       _SensorService_StreamAccelGyroMeasurements_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "back/internal/adapters/grpc/proto/sensor.proto",
}
