// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: back/internal/adapters/grpc/proto/sensor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckMode int32

const (
	AckMode_ACK_MODE_UNSPECIFIED AckMode = 0
	AckMode_ACK_MODE_FULL        AckMode = 1 // stats + erreurs (par défaut)
	AckMode_ACK_MODE_STATS_ONLY  AckMode = 2 // accepted/rejected uniquement
	AckMode_ACK_MODE_NONE        AckMode = 3 // fire-and-forget
)

// Enum value maps for AckMode.
var (
	AckMode_name = map[int32]string{
		0: "ACK_MODE_UNSPECIFIED",
		1: "ACK_MODE_FULL",
		2: "ACK_MODE_STATS_ONLY",
		3: "ACK_MODE_NONE",
	}
	AckMode_value = map[string]int32{
		"ACK_MODE_UNSPECIFIED": 0,
		"ACK_MODE_FULL":        1,
		"ACK_MODE_STATS_ONLY":  2,
		"ACK_MODE_NONE":        3,
	}
)

func (x AckMode) Enum() *AckMode {
	p := new(AckMode)
	*p = x
	return p
}

func (x AckMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckMode) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[0].Descriptor()
}

func (AckMode) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[0]
}

func (x AckMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckMode.Descriptor instead.
func (AckMode) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{0}
}

type IngestStatus int32

const (
	IngestStatus_INGEST_STATUS_UNSPECIFIED IngestStatus = 0
	IngestStatus_INGEST_STATUS_OK          IngestStatus = 1
	IngestStatus_INGEST_STATUS_PARTIAL     IngestStatus = 2
	IngestStatus_INGEST_STATUS_THROTTLED   IngestStatus = 3
	IngestStatus_INGEST_STATUS_REJECTED    IngestStatus = 4
)

// Enum value maps for IngestStatus.
var (
	IngestStatus_name = map[int32]string{
		0: "INGEST_STATUS_UNSPECIFIED",
		1: "INGEST_STATUS_OK",
		2: "INGEST_STATUS_PARTIAL",
		3: "INGEST_STATUS_THROTTLED",
		4: "INGEST_STATUS_REJECTED",
	}
	IngestStatus_value = map[string]int32{
		"INGEST_STATUS_UNSPECIFIED": 0,
		"INGEST_STATUS_OK":          1,
		"INGEST_STATUS_PARTIAL":     2,
		"INGEST_STATUS_THROTTLED":   3,
		"INGEST_STATUS_REJECTED":    4,
	}
)

func (x IngestStatus) Enum() *IngestStatus {
	p := new(IngestStatus)
	*p = x
	return p
}

func (x IngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[1].Descriptor()
}

func (IngestStatus) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[1]
}

func (x IngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestStatus.Descriptor instead.
func (IngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{1}
}

type RejectionCode int32

const (
	RejectionCode_UNKNOWN           RejectionCode = 0
	RejectionCode_INVALID_VALUE     RejectionCode = 1
	RejectionCode_TIMESTAMP_MISSING RejectionCode = 2
	RejectionCode_SENSOR_NOT_FOUND  RejectionCode = 3
)

// Enum value maps for RejectionCode.
var (
	RejectionCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_VALUE",
		2: "TIMESTAMP_MISSING",
		3: "SENSOR_NOT_FOUND",
	}
	RejectionCode_value = map[string]int32{
		"UNKNOWN":           0,
		"INVALID_VALUE":     1,
		"TIMESTAMP_MISSING": 2,
		"SENSOR_NOT_FOUND":  3,
	}
)

func (x RejectionCode) Enum() *RejectionCode {
	p := new(RejectionCode)
	*p = x
	return p
}

func (x RejectionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[2].Descriptor()
}

func (RejectionCode) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[2]
}

func (x RejectionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectionCode.Descriptor instead.
func (RejectionCode) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{2}
}

type IngestOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AckMode            AckMode                `protobuf:"varint,1,opt,name=ack_mode,json=ackMode,proto3,enum=sensor.AckMode" json:"ack_mode,omitempty"`
	MaxRejectedDetails *uint32                `protobuf:"varint,2,opt,name=max_rejected_details,json=maxRejectedDetails,proto3,oneof" json:"max_rejected_details,omitempty"`
	AckEveryN          *uint32                `protobuf:"varint,3,opt,name=ack_every_n,json=ackEveryN,proto3,oneof" json:"ack_every_n,omitempty"`
	AckMaxIntervalMs   *uint32                `protobuf:"varint,4,opt,name=ack_max_interval_ms,json=ackMaxIntervalMs,proto3,oneof" json:"ack_max_interval_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IngestOptions) Reset() {
	*x = IngestOptions{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestOptions) ProtoMessage() {}

func (x *IngestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestOptions.ProtoReflect.Descriptor instead.
func (*IngestOptions) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *IngestOptions) GetAckMode() AckMode {
	if x != nil {
		return x.AckMode
	}
	return AckMode_ACK_MODE_UNSPECIFIED
}

func (x *IngestOptions) GetMaxRejectedDetails() uint32 {
	if x != nil && x.MaxRejectedDetails != nil {
		return *x.MaxRejectedDetails
	}
	return 0
}

func (x *IngestOptions) GetAckEveryN() uint32 {
	if x != nil && x.AckEveryN != nil {
		return *x.AckEveryN
	}
	return 0
}

func (x *IngestOptions) GetAckMaxIntervalMs() uint32 {
	if x != nil && x.AckMaxIntervalMs != nil {
		return *x.AckMaxIntervalMs
	}
	return 0
}

type IngestAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected        uint64                 `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Status          IngestStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=sensor.IngestStatus" json:"status,omitempty"`
	Message         *string                `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	RejectedDetails []*RejectedDetail      `protobuf:"bytes,5,rep,name=rejected_details,json=rejectedDetails,proto3" json:"rejected_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *IngestAck) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestAck) GetRejected() uint64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestAck) GetStatus() IngestStatus {
	if x != nil {
		return x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

func (x *IngestAck) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *IngestAck) GetRejectedDetails() []*RejectedDetail {
	if x != nil {
		return x.RejectedDetails
	}
	return nil
}

type RejectedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Code          RejectionCode          `protobuf:"varint,2,opt,name=code,proto3,enum=sensor.RejectionCode" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedDetail) Reset() {
	*x = RejectedDetail{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedDetail) ProtoMessage() {}

func (x *RejectedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedDetail.ProtoReflect.Descriptor instead.
func (*RejectedDetail) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *RejectedDetail) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *RejectedDetail) GetCode() RejectionCode {
	if x != nil {
		return x.Code
	}
	return RejectionCode_UNKNOWN
}

func (x *RejectedDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectedDetail) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SensorMeasurementsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Sensors       []*SensorMeasurementsForSensor `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty"`
	Options       *IngestOptions                 `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorMeasurementsRequest) Reset() {
	*x = SensorMeasurementsRequest{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorMeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorMeasurementsRequest) ProtoMessage() {}

func (x *SensorMeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorMeasurementsRequest.ProtoReflect.Descriptor instead.
func (*SensorMeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *SensorMeasurementsRequest) GetSensors() []*SensorMeasurementsForSensor {
	if x != nil {
		return x.Sensors
	}
	return nil
}

func (x *SensorMeasurementsRequest) GetOptions() *IngestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SensorMeasurementsForSensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Measurements  []*SensorMeasurement   `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorMeasurementsForSensor) Reset() {
	*x = SensorMeasurementsForSensor{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorMeasurementsForSensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorMeasurementsForSensor) ProtoMessage() {}

func (x *SensorMeasurementsForSensor) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorMeasurementsForSensor.ProtoReflect.Descriptor instead.
func (*SensorMeasurementsForSensor) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *SensorMeasurementsForSensor) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *SensorMeasurementsForSensor) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SensorMeasurementsForSensor) GetMeasurements() []*SensorMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type SensorMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeasuredAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=measured_at,json=measuredAt,proto3,oneof" json:"measured_at,omitempty"`
	Values        map[string]*anypb.Any  `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorMeasurement) Reset() {
	*x = SensorMeasurement{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorMeasurement) ProtoMessage() {}

func (x *SensorMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorMeasurement.ProtoReflect.Descriptor instead.
func (*SensorMeasurement) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{5}
}

func (x *SensorMeasurement) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *SensorMeasurement) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_back_internal_adapters_grpc_proto_sensor_proto protoreflect.FileDescriptor

const file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc = "" +
	"\n" +
	".back/internal/adapters/grpc/proto/sensor.proto\x12\x06sensor\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n" +
	"\rIngestOptions\x12*\n" +
	"\back_mode\x18\x01 \x01(\x0e2\x0f.sensor.AckModeR\aackMode\x125\n" +
	"\x14max_rejected_details\x18\x02 \x01(\rH\x00R\x12maxRejectedDetails\x88\x01\x01\x12#\n" +
	"\vack_every_n\x18\x03 \x01(\rH\x01R\tackEveryN\x88\x01\x01\x122\n" +
	"\x13ack_max_interval_ms\x18\x04 \x01(\rH\x02R\x10ackMaxIntervalMs\x88\x01\x01B\x17\n" +
	"\x15_max_rejected_detailsB\x0e\n" +
	"\f_ack_every_nB\x16\n" +
	"\x14_ack_max_interval_ms\"\xdf\x01\n" +
	"\tIngestAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x04R\brejected\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.sensor.IngestStatusR\x06status\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessage\x88\x01\x01\x12A\n" +
	"\x10rejected_details\x18\x05 \x03(\v2\x16.sensor.RejectedDetailR\x0frejectedDetailsB\n" +
	"\n" +
	"\b_message\"\x86\x01\n" +
	"\x0eRejectedDetail\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12)\n" +
	"\x04code\x18\x02 \x01(\x0e2\x15.sensor.RejectionCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\"\x9c\x01\n" +
	"\x19SensorMeasurementsRequest\x12=\n" +
	"\asensors\x18\x01 \x03(\v2#.sensor.SensorMeasurementsForSensorR\asensors\x124\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.sensor.IngestOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\x98\x01\n" +
	"\x1bSensorMeasurementsForSensor\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12=\n" +
	"\fmeasurements\x18\x03 \x03(\v2\x19.sensor.SensorMeasurementR\fmeasurements\"\xf5\x01\n" +
	"\x11SensorMeasurement\x12@\n" +
	"\vmeasured_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"measuredAt\x88\x01\x01\x12=\n" +
	"\x06values\x18\x02 \x03(\v2%.sensor.SensorMeasurement.ValuesEntryR\x06values\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01B\x0e\n" +
	"\f_measured_at*b\n" +
	"\aAckMode\x12\x18\n" +
	"\x14ACK_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_MODE_FULL\x10\x01\x12\x17\n" +
	"\x13ACK_MODE_STATS_ONLY\x10\x02\x12\x11\n" +
	"\rACK_MODE_NONE\x10\x03*\x97\x01\n" +
	"\fIngestStatus\x12\x1d\n" +
	"\x19INGEST_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10INGEST_STATUS_OK\x10\x01\x12\x19\n" +
	"\x15INGEST_STATUS_PARTIAL\x10\x02\x12\x1b\n" +
	"\x17INGEST_STATUS_THROTTLED\x10\x03\x12\x1a\n" +
	"\x16INGEST_STATUS_REJECTED\x10\x04*\\\n" +
	"\rRejectionCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rINVALID_VALUE\x10\x01\x12\x15\n" +
	"\x11TIMESTAMP_MISSING\x10\x02\x12\x14\n" +
	"\x10SENSOR_NOT_FOUND\x10\x032\xaa\x01\n" +
	"\rSensorService\x12N\n" +
	"\x12StreamMeasurements\x12!.sensor.SensorMeasurementsRequest\x1a\x11.sensor.IngestAck(\x010\x01\x12I\n" +
	"\x11UnaryMeasurements\x12!.sensor.SensorMeasurementsRequest\x1a\x11.sensor.IngestAckB=Z;github.com/brice-74/sensorflow/internal/adapters/grpc/protob\x06proto3"

var (
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescOnce sync.Once
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData []byte
)

func file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP() []byte {
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescOnce.Do(func() {
		file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc), len(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc)))
	})
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData
}

var file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_back_internal_adapters_grpc_proto_sensor_proto_goTypes = []any{
	(AckMode)(0),                        // 0: sensor.AckMode
	(IngestStatus)(0),                   // 1: sensor.IngestStatus
	(RejectionCode)(0),                  // 2: sensor.RejectionCode
	(*IngestOptions)(nil),               // 3: sensor.IngestOptions
	(*IngestAck)(nil),                   // 4: sensor.IngestAck
	(*RejectedDetail)(nil),              // 5: sensor.RejectedDetail
	(*SensorMeasurementsRequest)(nil),   // 6: sensor.SensorMeasurementsRequest
	(*SensorMeasurementsForSensor)(nil), // 7: sensor.SensorMeasurementsForSensor
	(*SensorMeasurement)(nil),           // 8: sensor.SensorMeasurement
	nil,                                 // 9: sensor.SensorMeasurement.ValuesEntry
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
	(*anypb.Any)(nil),                   // 11: google.protobuf.Any
}
var file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs = []int32{
	0,  // 0: sensor.IngestOptions.ack_mode:type_name -> sensor.AckMode
	1,  // 1: sensor.IngestAck.status:type_name -> sensor.IngestStatus
	5,  // 2: sensor.IngestAck.rejected_details:type_name -> sensor.RejectedDetail
	2,  // 3: sensor.RejectedDetail.code:type_name -> sensor.RejectionCode
	7,  // 4: sensor.SensorMeasurementsRequest.sensors:type_name -> sensor.SensorMeasurementsForSensor
	3,  // 5: sensor.SensorMeasurementsRequest.options:type_name -> sensor.IngestOptions
	8,  // 6: sensor.SensorMeasurementsForSensor.measurements:type_name -> sensor.SensorMeasurement
	10, // 7: sensor.SensorMeasurement.measured_at:type_name -> google.protobuf.Timestamp
	9,  // 8: sensor.SensorMeasurement.values:type_name -> sensor.SensorMeasurement.ValuesEntry
	11, // 9: sensor.SensorMeasurement.ValuesEntry.value:type_name -> google.protobuf.Any
	6,  // 10: sensor.SensorService.StreamMeasurements:input_type -> sensor.SensorMeasurementsRequest
	6,  // 11: sensor.SensorService.UnaryMeasurements:input_type -> sensor.SensorMeasurementsRequest
	4,  // 12: sensor.SensorService.StreamMeasurements:output_type -> sensor.IngestAck
	4,  // 13: sensor.SensorService.UnaryMeasurements:output_type -> sensor.IngestAck
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_back_internal_adapters_grpc_proto_sensor_proto_init() }
func file_back_internal_adapters_grpc_proto_sensor_proto_init() {
	if File_back_internal_adapters_grpc_proto_sensor_proto != nil {
		return
	}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[3].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc), len(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_back_internal_adapters_grpc_proto_sensor_proto_goTypes,
		DependencyIndexes: file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs,
		EnumInfos:         file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes,
		MessageInfos:      file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes,
	}.Build()
	File_back_internal_adapters_grpc_proto_sensor_proto = out.File
	file_back_internal_adapters_grpc_proto_sensor_proto_goTypes = nil
	file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs = nil
}
