// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: back/internal/adapters/grpc/proto/sensor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorMeasurementsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string represents a sensor ID
	Values        map[string]*SensorMeasurementsList `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorMeasurementsRequest) Reset() {
	*x = SensorMeasurementsRequest{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorMeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorMeasurementsRequest) ProtoMessage() {}

func (x *SensorMeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorMeasurementsRequest.ProtoReflect.Descriptor instead.
func (*SensorMeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorMeasurementsRequest) GetValues() map[string]*SensorMeasurementsList {
	if x != nil {
		return x.Values
	}
	return nil
}

type SensorMeasurementsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurements  []*SensorMeasurements  `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorMeasurementsList) Reset() {
	*x = SensorMeasurementsList{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorMeasurementsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorMeasurementsList) ProtoMessage() {}

func (x *SensorMeasurementsList) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorMeasurementsList.ProtoReflect.Descriptor instead.
func (*SensorMeasurementsList) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *SensorMeasurementsList) GetMeasurements() []*SensorMeasurements {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type SensorMeasurements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Values        map[string]*anypb.Any  `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorMeasurements) Reset() {
	*x = SensorMeasurements{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorMeasurements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorMeasurements) ProtoMessage() {}

func (x *SensorMeasurements) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorMeasurements.ProtoReflect.Descriptor instead.
func (*SensorMeasurements) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *SensorMeasurements) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SensorMeasurements) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_back_internal_adapters_grpc_proto_sensor_proto protoreflect.FileDescriptor

const file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc = "" +
	"\n" +
	".back/internal/adapters/grpc/proto/sensor.proto\x12\x06sensor\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\"\xbd\x01\n" +
	"\x19SensorMeasurementsRequest\x12E\n" +
	"\x06values\x18\x01 \x03(\v2-.sensor.SensorMeasurementsRequest.ValuesEntryR\x06values\x1aY\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.sensor.SensorMeasurementsListR\x05value:\x028\x01\"X\n" +
	"\x16SensorMeasurementsList\x12>\n" +
	"\fmeasurements\x18\x01 \x03(\v2\x1a.sensor.SensorMeasurementsR\fmeasurements\"\xc3\x01\n" +
	"\x12SensorMeasurements\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12>\n" +
	"\x06values\x18\x03 \x03(\v2&.sensor.SensorMeasurements.ValuesEntryR\x06values\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x012\xb2\x01\n" +
	"\rSensorService\x12Q\n" +
	"\x12StreamMeasurements\x12!.sensor.SensorMeasurementsRequest\x1a\x16.google.protobuf.Empty(\x01\x12N\n" +
	"\x11UnaryMeasurements\x12!.sensor.SensorMeasurementsRequest\x1a\x16.google.protobuf.EmptyB=Z;github.com/brice-74/sensorflow/internal/adapters/grpc/protob\x06proto3"

var (
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescOnce sync.Once
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData []byte
)

func file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP() []byte {
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescOnce.Do(func() {
		file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc), len(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc)))
	})
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData
}

var file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_back_internal_adapters_grpc_proto_sensor_proto_goTypes = []any{
	(*SensorMeasurementsRequest)(nil), // 0: sensor.SensorMeasurementsRequest
	(*SensorMeasurementsList)(nil),    // 1: sensor.SensorMeasurementsList
	(*SensorMeasurements)(nil),        // 2: sensor.SensorMeasurements
	nil,                               // 3: sensor.SensorMeasurementsRequest.ValuesEntry
	nil,                               // 4: sensor.SensorMeasurements.ValuesEntry
	(*anypb.Any)(nil),                 // 5: google.protobuf.Any
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
}
var file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs = []int32{
	3, // 0: sensor.SensorMeasurementsRequest.values:type_name -> sensor.SensorMeasurementsRequest.ValuesEntry
	2, // 1: sensor.SensorMeasurementsList.measurements:type_name -> sensor.SensorMeasurements
	4, // 2: sensor.SensorMeasurements.values:type_name -> sensor.SensorMeasurements.ValuesEntry
	1, // 3: sensor.SensorMeasurementsRequest.ValuesEntry.value:type_name -> sensor.SensorMeasurementsList
	5, // 4: sensor.SensorMeasurements.ValuesEntry.value:type_name -> google.protobuf.Any
	0, // 5: sensor.SensorService.StreamMeasurements:input_type -> sensor.SensorMeasurementsRequest
	0, // 6: sensor.SensorService.UnaryMeasurements:input_type -> sensor.SensorMeasurementsRequest
	6, // 7: sensor.SensorService.StreamMeasurements:output_type -> google.protobuf.Empty
	6, // 8: sensor.SensorService.UnaryMeasurements:output_type -> google.protobuf.Empty
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_back_internal_adapters_grpc_proto_sensor_proto_init() }
func file_back_internal_adapters_grpc_proto_sensor_proto_init() {
	if File_back_internal_adapters_grpc_proto_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc), len(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_back_internal_adapters_grpc_proto_sensor_proto_goTypes,
		DependencyIndexes: file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs,
		MessageInfos:      file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes,
	}.Build()
	File_back_internal_adapters_grpc_proto_sensor_proto = out.File
	file_back_internal_adapters_grpc_proto_sensor_proto_goTypes = nil
	file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs = nil
}
