// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: back/internal/adapters/grpc/proto/sensor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorService_StreamMeasurements_FullMethodName = "/sensor.SensorService/StreamMeasurements"
	SensorService_UnaryMeasurements_FullMethodName  = "/sensor.SensorService/UnaryMeasurements"
)

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorServiceClient interface {
	StreamMeasurements(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SensorMeasurementsRequest, IngestAck], error)
	UnaryMeasurements(ctx context.Context, in *SensorMeasurementsRequest, opts ...grpc.CallOption) (*IngestAck, error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) StreamMeasurements(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SensorMeasurementsRequest, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[0], SensorService_StreamMeasurements_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SensorMeasurementsRequest, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_StreamMeasurementsClient = grpc.BidiStreamingClient[SensorMeasurementsRequest, IngestAck]

func (c *sensorServiceClient) UnaryMeasurements(ctx context.Context, in *SensorMeasurementsRequest, opts ...grpc.CallOption) (*IngestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAck)
	err := c.cc.Invoke(ctx, SensorService_UnaryMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServiceServer is the server API for SensorService service.
// All implementations must embed UnimplementedSensorServiceServer
// for forward compatibility.
type SensorServiceServer interface {
	StreamMeasurements(grpc.BidiStreamingServer[SensorMeasurementsRequest, IngestAck]) error
	UnaryMeasurements(context.Context, *SensorMeasurementsRequest) (*IngestAck, error)
	mustEmbedUnimplementedSensorServiceServer()
}

// UnimplementedSensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorServiceServer struct{}

func (UnimplementedSensorServiceServer) StreamMeasurements(grpc.BidiStreamingServer[SensorMeasurementsRequest, IngestAck]) error {
	return status.Error(codes.Unimplemented, "method StreamMeasurements not implemented")
}
func (UnimplementedSensorServiceServer) UnaryMeasurements(context.Context, *SensorMeasurementsRequest) (*IngestAck, error) {
	return nil, status.Error(codes.Unimplemented, "method UnaryMeasurements not implemented")
}
func (UnimplementedSensorServiceServer) mustEmbedUnimplementedSensorServiceServer() {}
func (UnimplementedSensorServiceServer) testEmbeddedByValue()                       {}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	// If the following call panics, it indicates UnimplementedSensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_StreamMeasurements_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServiceServer).StreamMeasurements(&grpc.GenericServerStream[SensorMeasurementsRequest, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorService_StreamMeasurementsServer = grpc.BidiStreamingServer[SensorMeasurementsRequest, IngestAck]

func _SensorService_UnaryMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorMeasurementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).UnaryMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_UnaryMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).UnaryMeasurements(ctx, req.(*SensorMeasurementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sensor.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryMeasurements",
			Handler:    _SensorService_UnaryMeasurements_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMeasurements",
			Handler:       _SensorService_StreamMeasurements_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "back/internal/adapters/grpc/proto/sensor.proto",
}
