// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: back/internal/adapters/grpc/proto/sensor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckMode int32

const (
	AckMode_ACK_MODE_UNSPECIFIED AckMode = 0
	AckMode_ACK_MODE_FULL        AckMode = 1 // stats + erreurs (par défaut)
	AckMode_ACK_MODE_STATS_ONLY  AckMode = 2 // accepted/rejected only
	AckMode_ACK_MODE_NONE        AckMode = 3 // fire-and-forget
)

// Enum value maps for AckMode.
var (
	AckMode_name = map[int32]string{
		0: "ACK_MODE_UNSPECIFIED",
		1: "ACK_MODE_FULL",
		2: "ACK_MODE_STATS_ONLY",
		3: "ACK_MODE_NONE",
	}
	AckMode_value = map[string]int32{
		"ACK_MODE_UNSPECIFIED": 0,
		"ACK_MODE_FULL":        1,
		"ACK_MODE_STATS_ONLY":  2,
		"ACK_MODE_NONE":        3,
	}
)

func (x AckMode) Enum() *AckMode {
	p := new(AckMode)
	*p = x
	return p
}

func (x AckMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckMode) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[0].Descriptor()
}

func (AckMode) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[0]
}

func (x AckMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckMode.Descriptor instead.
func (AckMode) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{0}
}

type LogicalIngestStatus int32

const (
	LogicalIngestStatus_LOGICAL_INGEST_STATUS_UNSPECIFIED LogicalIngestStatus = 0
	LogicalIngestStatus_LOGICAL_INGEST_STATUS_OK          LogicalIngestStatus = 1
	LogicalIngestStatus_LOGICAL_INGEST_STATUS_PARTIAL     LogicalIngestStatus = 2
	LogicalIngestStatus_LOGICAL_INGEST_STATUS_REJECTED    LogicalIngestStatus = 3
)

// Enum value maps for LogicalIngestStatus.
var (
	LogicalIngestStatus_name = map[int32]string{
		0: "LOGICAL_INGEST_STATUS_UNSPECIFIED",
		1: "LOGICAL_INGEST_STATUS_OK",
		2: "LOGICAL_INGEST_STATUS_PARTIAL",
		3: "LOGICAL_INGEST_STATUS_REJECTED",
	}
	LogicalIngestStatus_value = map[string]int32{
		"LOGICAL_INGEST_STATUS_UNSPECIFIED": 0,
		"LOGICAL_INGEST_STATUS_OK":          1,
		"LOGICAL_INGEST_STATUS_PARTIAL":     2,
		"LOGICAL_INGEST_STATUS_REJECTED":    3,
	}
)

func (x LogicalIngestStatus) Enum() *LogicalIngestStatus {
	p := new(LogicalIngestStatus)
	*p = x
	return p
}

func (x LogicalIngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalIngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[1].Descriptor()
}

func (LogicalIngestStatus) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[1]
}

func (x LogicalIngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalIngestStatus.Descriptor instead.
func (LogicalIngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{1}
}

type TechnicalIngestStatus int32

const (
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_UNSPECIFIED    TechnicalIngestStatus = 0
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_OK             TechnicalIngestStatus = 1
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_PENDING        TechnicalIngestStatus = 2
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_RETRYING_MAIN  TechnicalIngestStatus = 3
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_RETRYING_LEVEL TechnicalIngestStatus = 4
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_LEVEL_FALLBACK TechnicalIngestStatus = 5
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_ERROR          TechnicalIngestStatus = 6
	TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_STOPPED        TechnicalIngestStatus = 7
)

// Enum value maps for TechnicalIngestStatus.
var (
	TechnicalIngestStatus_name = map[int32]string{
		0: "TECHNICAL_INGEST_STATUS_UNSPECIFIED",
		1: "TECHNICAL_INGEST_STATUS_OK",
		2: "TECHNICAL_INGEST_STATUS_PENDING",
		3: "TECHNICAL_INGEST_STATUS_RETRYING_MAIN",
		4: "TECHNICAL_INGEST_STATUS_RETRYING_LEVEL",
		5: "TECHNICAL_INGEST_STATUS_LEVEL_FALLBACK",
		6: "TECHNICAL_INGEST_STATUS_ERROR",
		7: "TECHNICAL_INGEST_STATUS_STOPPED",
	}
	TechnicalIngestStatus_value = map[string]int32{
		"TECHNICAL_INGEST_STATUS_UNSPECIFIED":    0,
		"TECHNICAL_INGEST_STATUS_OK":             1,
		"TECHNICAL_INGEST_STATUS_PENDING":        2,
		"TECHNICAL_INGEST_STATUS_RETRYING_MAIN":  3,
		"TECHNICAL_INGEST_STATUS_RETRYING_LEVEL": 4,
		"TECHNICAL_INGEST_STATUS_LEVEL_FALLBACK": 5,
		"TECHNICAL_INGEST_STATUS_ERROR":          6,
		"TECHNICAL_INGEST_STATUS_STOPPED":        7,
	}
)

func (x TechnicalIngestStatus) Enum() *TechnicalIngestStatus {
	p := new(TechnicalIngestStatus)
	*p = x
	return p
}

func (x TechnicalIngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TechnicalIngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[2].Descriptor()
}

func (TechnicalIngestStatus) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[2]
}

func (x TechnicalIngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TechnicalIngestStatus.Descriptor instead.
func (TechnicalIngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{2}
}

type RejectionCode int32

const (
	RejectionCode_UNKNOWN                        RejectionCode = 0
	RejectionCode_INVALID_SENSOR_ID              RejectionCode = 1
	RejectionCode_UNKNOWN_SENSOR_OR_UNKNOWN_PLAN RejectionCode = 2
)

// Enum value maps for RejectionCode.
var (
	RejectionCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_SENSOR_ID",
		2: "UNKNOWN_SENSOR_OR_UNKNOWN_PLAN",
	}
	RejectionCode_value = map[string]int32{
		"UNKNOWN":                        0,
		"INVALID_SENSOR_ID":              1,
		"UNKNOWN_SENSOR_OR_UNKNOWN_PLAN": 2,
	}
)

func (x RejectionCode) Enum() *RejectionCode {
	p := new(RejectionCode)
	*p = x
	return p
}

func (x RejectionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[3].Descriptor()
}

func (RejectionCode) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[3]
}

func (x RejectionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectionCode.Descriptor instead.
func (RejectionCode) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{3}
}

type TemperatureUnit int32

const (
	TemperatureUnit_CELSIUS    TemperatureUnit = 0 // °C
	TemperatureUnit_FAHRENHEIT TemperatureUnit = 1 // °F
	TemperatureUnit_KELVIN     TemperatureUnit = 2 // K
)

// Enum value maps for TemperatureUnit.
var (
	TemperatureUnit_name = map[int32]string{
		0: "CELSIUS",
		1: "FAHRENHEIT",
		2: "KELVIN",
	}
	TemperatureUnit_value = map[string]int32{
		"CELSIUS":    0,
		"FAHRENHEIT": 1,
		"KELVIN":     2,
	}
)

func (x TemperatureUnit) Enum() *TemperatureUnit {
	p := new(TemperatureUnit)
	*p = x
	return p
}

func (x TemperatureUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemperatureUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[4].Descriptor()
}

func (TemperatureUnit) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[4]
}

func (x TemperatureUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemperatureUnit.Descriptor instead.
func (TemperatureUnit) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{4}
}

type AccelUnit int32

const (
	AccelUnit_M_S2 AccelUnit = 0 // m/s²
	AccelUnit_G    AccelUnit = 1 // g
)

// Enum value maps for AccelUnit.
var (
	AccelUnit_name = map[int32]string{
		0: "M_S2",
		1: "G",
	}
	AccelUnit_value = map[string]int32{
		"M_S2": 0,
		"G":    1,
	}
)

func (x AccelUnit) Enum() *AccelUnit {
	p := new(AccelUnit)
	*p = x
	return p
}

func (x AccelUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccelUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[5].Descriptor()
}

func (AccelUnit) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[5]
}

func (x AccelUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccelUnit.Descriptor instead.
func (AccelUnit) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{5}
}

type GyroUnit int32

const (
	GyroUnit_DEG_S GyroUnit = 0 // °/s
	GyroUnit_RAD_S GyroUnit = 1 // rad/s
)

// Enum value maps for GyroUnit.
var (
	GyroUnit_name = map[int32]string{
		0: "DEG_S",
		1: "RAD_S",
	}
	GyroUnit_value = map[string]int32{
		"DEG_S": 0,
		"RAD_S": 1,
	}
)

func (x GyroUnit) Enum() *GyroUnit {
	p := new(GyroUnit)
	*p = x
	return p
}

func (x GyroUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GyroUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[6].Descriptor()
}

func (GyroUnit) Type() protoreflect.EnumType {
	return &file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes[6]
}

func (x GyroUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GyroUnit.Descriptor instead.
func (GyroUnit) EnumDescriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{6}
}

type IngestOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AckMode            AckMode                `protobuf:"varint,1,opt,name=ack_mode,json=ackMode,proto3,enum=sensor.AckMode" json:"ack_mode,omitempty"`
	MaxRejectedDetails *uint32                `protobuf:"varint,2,opt,name=max_rejected_details,json=maxRejectedDetails,proto3,oneof" json:"max_rejected_details,omitempty"`
	AckEveryN          *uint32                `protobuf:"varint,3,opt,name=ack_every_n,json=ackEveryN,proto3,oneof" json:"ack_every_n,omitempty"`
	AckMaxIntervalMs   *uint32                `protobuf:"varint,4,opt,name=ack_max_interval_ms,json=ackMaxIntervalMs,proto3,oneof" json:"ack_max_interval_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IngestOptions) Reset() {
	*x = IngestOptions{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestOptions) ProtoMessage() {}

func (x *IngestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestOptions.ProtoReflect.Descriptor instead.
func (*IngestOptions) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *IngestOptions) GetAckMode() AckMode {
	if x != nil {
		return x.AckMode
	}
	return AckMode_ACK_MODE_UNSPECIFIED
}

func (x *IngestOptions) GetMaxRejectedDetails() uint32 {
	if x != nil && x.MaxRejectedDetails != nil {
		return *x.MaxRejectedDetails
	}
	return 0
}

func (x *IngestOptions) GetAckEveryN() uint32 {
	if x != nil && x.AckEveryN != nil {
		return *x.AckEveryN
	}
	return 0
}

func (x *IngestOptions) GetAckMaxIntervalMs() uint32 {
	if x != nil && x.AckMaxIntervalMs != nil {
		return *x.AckMaxIntervalMs
	}
	return 0
}

type IngestAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected        uint64                 `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	LogicalStatus   LogicalIngestStatus    `protobuf:"varint,3,opt,name=logical_status,json=logicalStatus,proto3,enum=sensor.LogicalIngestStatus" json:"logical_status,omitempty"`
	TechnicalStatus TechnicalIngestStatus  `protobuf:"varint,4,opt,name=technical_status,json=technicalStatus,proto3,enum=sensor.TechnicalIngestStatus" json:"technical_status,omitempty"`
	Message         *string                `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	RejectedDetails []*RejectedDetail      `protobuf:"bytes,6,rep,name=rejected_details,json=rejectedDetails,proto3" json:"rejected_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *IngestAck) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestAck) GetRejected() uint64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestAck) GetLogicalStatus() LogicalIngestStatus {
	if x != nil {
		return x.LogicalStatus
	}
	return LogicalIngestStatus_LOGICAL_INGEST_STATUS_UNSPECIFIED
}

func (x *IngestAck) GetTechnicalStatus() TechnicalIngestStatus {
	if x != nil {
		return x.TechnicalStatus
	}
	return TechnicalIngestStatus_TECHNICAL_INGEST_STATUS_UNSPECIFIED
}

func (x *IngestAck) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *IngestAck) GetRejectedDetails() []*RejectedDetail {
	if x != nil {
		return x.RejectedDetails
	}
	return nil
}

type RejectedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Code          RejectionCode          `protobuf:"varint,2,opt,name=code,proto3,enum=sensor.RejectionCode" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedDetail) Reset() {
	*x = RejectedDetail{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedDetail) ProtoMessage() {}

func (x *RejectedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedDetail.ProtoReflect.Descriptor instead.
func (*RejectedDetail) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *RejectedDetail) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *RejectedDetail) GetCode() RejectionCode {
	if x != nil {
		return x.Code
	}
	return RejectionCode_UNKNOWN
}

func (x *RejectedDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectedDetail) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CustomMeasurementsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Sensors       []*CustomMeasurementsForSensor `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty"`
	Options       *IngestOptions                 `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomMeasurementsRequest) Reset() {
	*x = CustomMeasurementsRequest{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomMeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomMeasurementsRequest) ProtoMessage() {}

func (x *CustomMeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomMeasurementsRequest.ProtoReflect.Descriptor instead.
func (*CustomMeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *CustomMeasurementsRequest) GetSensors() []*CustomMeasurementsForSensor {
	if x != nil {
		return x.Sensors
	}
	return nil
}

func (x *CustomMeasurementsRequest) GetOptions() *IngestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type CustomMeasurementsForSensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Measurements  []*CustomMeasurement   `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomMeasurementsForSensor) Reset() {
	*x = CustomMeasurementsForSensor{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomMeasurementsForSensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomMeasurementsForSensor) ProtoMessage() {}

func (x *CustomMeasurementsForSensor) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomMeasurementsForSensor.ProtoReflect.Descriptor instead.
func (*CustomMeasurementsForSensor) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *CustomMeasurementsForSensor) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *CustomMeasurementsForSensor) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *CustomMeasurementsForSensor) GetMeasurements() []*CustomMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type CustomMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeasuredAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	Values        map[string]*anypb.Any  `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomMeasurement) Reset() {
	*x = CustomMeasurement{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomMeasurement) ProtoMessage() {}

func (x *CustomMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomMeasurement.ProtoReflect.Descriptor instead.
func (*CustomMeasurement) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{5}
}

func (x *CustomMeasurement) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *CustomMeasurement) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

type IngestAccelGyroOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IngestOptions   *IngestOptions         `protobuf:"bytes,1,opt,name=ingest_options,json=ingestOptions,proto3,oneof" json:"ingest_options,omitempty"`
	AccelUnit       *AccelUnit             `protobuf:"varint,2,opt,name=accel_unit,json=accelUnit,proto3,enum=sensor.AccelUnit,oneof" json:"accel_unit,omitempty"`
	GyroUnit        *GyroUnit              `protobuf:"varint,3,opt,name=gyro_unit,json=gyroUnit,proto3,enum=sensor.GyroUnit,oneof" json:"gyro_unit,omitempty"`
	TemperatureUnit *TemperatureUnit       `protobuf:"varint,4,opt,name=temperature_unit,json=temperatureUnit,proto3,enum=sensor.TemperatureUnit,oneof" json:"temperature_unit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestAccelGyroOptions) Reset() {
	*x = IngestAccelGyroOptions{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAccelGyroOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAccelGyroOptions) ProtoMessage() {}

func (x *IngestAccelGyroOptions) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAccelGyroOptions.ProtoReflect.Descriptor instead.
func (*IngestAccelGyroOptions) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{6}
}

func (x *IngestAccelGyroOptions) GetIngestOptions() *IngestOptions {
	if x != nil {
		return x.IngestOptions
	}
	return nil
}

func (x *IngestAccelGyroOptions) GetAccelUnit() AccelUnit {
	if x != nil && x.AccelUnit != nil {
		return *x.AccelUnit
	}
	return AccelUnit_M_S2
}

func (x *IngestAccelGyroOptions) GetGyroUnit() GyroUnit {
	if x != nil && x.GyroUnit != nil {
		return *x.GyroUnit
	}
	return GyroUnit_DEG_S
}

func (x *IngestAccelGyroOptions) GetTemperatureUnit() TemperatureUnit {
	if x != nil && x.TemperatureUnit != nil {
		return *x.TemperatureUnit
	}
	return TemperatureUnit_CELSIUS
}

type AccelGyroMeasurementsRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Sensors       []*AccelGyroMeasurementsForSensor `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty"`
	Options       *IngestAccelGyroOptions           `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccelGyroMeasurementsRequest) Reset() {
	*x = AccelGyroMeasurementsRequest{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccelGyroMeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccelGyroMeasurementsRequest) ProtoMessage() {}

func (x *AccelGyroMeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccelGyroMeasurementsRequest.ProtoReflect.Descriptor instead.
func (*AccelGyroMeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{7}
}

func (x *AccelGyroMeasurementsRequest) GetSensors() []*AccelGyroMeasurementsForSensor {
	if x != nil {
		return x.Sensors
	}
	return nil
}

func (x *AccelGyroMeasurementsRequest) GetOptions() *IngestAccelGyroOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type AccelGyroMeasurementsForSensor struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SensorId      string                  `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Measurements  []*AccelGyroMeasurement `protobuf:"bytes,2,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccelGyroMeasurementsForSensor) Reset() {
	*x = AccelGyroMeasurementsForSensor{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccelGyroMeasurementsForSensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccelGyroMeasurementsForSensor) ProtoMessage() {}

func (x *AccelGyroMeasurementsForSensor) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccelGyroMeasurementsForSensor.ProtoReflect.Descriptor instead.
func (*AccelGyroMeasurementsForSensor) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{8}
}

func (x *AccelGyroMeasurementsForSensor) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *AccelGyroMeasurementsForSensor) GetMeasurements() []*AccelGyroMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type AccelGyroMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeasuredAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	AccelX        float64                `protobuf:"fixed64,2,opt,name=accel_x,json=accelX,proto3" json:"accel_x,omitempty"`
	AccelY        float64                `protobuf:"fixed64,3,opt,name=accel_y,json=accelY,proto3" json:"accel_y,omitempty"`
	AccelZ        float64                `protobuf:"fixed64,4,opt,name=accel_z,json=accelZ,proto3" json:"accel_z,omitempty"`
	GyroX         float64                `protobuf:"fixed64,5,opt,name=gyro_x,json=gyroX,proto3" json:"gyro_x,omitempty"`
	GyroY         float64                `protobuf:"fixed64,6,opt,name=gyro_y,json=gyroY,proto3" json:"gyro_y,omitempty"`
	GyroZ         float64                `protobuf:"fixed64,7,opt,name=gyro_z,json=gyroZ,proto3" json:"gyro_z,omitempty"`
	Temperature   *float64               `protobuf:"fixed64,8,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	VibrationRms  *float64               `protobuf:"fixed64,9,opt,name=vibration_rms,json=vibrationRms,proto3,oneof" json:"vibration_rms,omitempty"`
	VibrationPeak *float64               `protobuf:"fixed64,10,opt,name=vibration_peak,json=vibrationPeak,proto3,oneof" json:"vibration_peak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccelGyroMeasurement) Reset() {
	*x = AccelGyroMeasurement{}
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccelGyroMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccelGyroMeasurement) ProtoMessage() {}

func (x *AccelGyroMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccelGyroMeasurement.ProtoReflect.Descriptor instead.
func (*AccelGyroMeasurement) Descriptor() ([]byte, []int) {
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP(), []int{9}
}

func (x *AccelGyroMeasurement) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *AccelGyroMeasurement) GetAccelX() float64 {
	if x != nil {
		return x.AccelX
	}
	return 0
}

func (x *AccelGyroMeasurement) GetAccelY() float64 {
	if x != nil {
		return x.AccelY
	}
	return 0
}

func (x *AccelGyroMeasurement) GetAccelZ() float64 {
	if x != nil {
		return x.AccelZ
	}
	return 0
}

func (x *AccelGyroMeasurement) GetGyroX() float64 {
	if x != nil {
		return x.GyroX
	}
	return 0
}

func (x *AccelGyroMeasurement) GetGyroY() float64 {
	if x != nil {
		return x.GyroY
	}
	return 0
}

func (x *AccelGyroMeasurement) GetGyroZ() float64 {
	if x != nil {
		return x.GyroZ
	}
	return 0
}

func (x *AccelGyroMeasurement) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *AccelGyroMeasurement) GetVibrationRms() float64 {
	if x != nil && x.VibrationRms != nil {
		return *x.VibrationRms
	}
	return 0
}

func (x *AccelGyroMeasurement) GetVibrationPeak() float64 {
	if x != nil && x.VibrationPeak != nil {
		return *x.VibrationPeak
	}
	return 0
}

var File_back_internal_adapters_grpc_proto_sensor_proto protoreflect.FileDescriptor

const file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc = "" +
	"\n" +
	".back/internal/adapters/grpc/proto/sensor.proto\x12\x06sensor\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n" +
	"\rIngestOptions\x12*\n" +
	"\back_mode\x18\x01 \x01(\x0e2\x0f.sensor.AckModeR\aackMode\x125\n" +
	"\x14max_rejected_details\x18\x02 \x01(\rH\x00R\x12maxRejectedDetails\x88\x01\x01\x12#\n" +
	"\vack_every_n\x18\x03 \x01(\rH\x01R\tackEveryN\x88\x01\x01\x122\n" +
	"\x13ack_max_interval_ms\x18\x04 \x01(\rH\x02R\x10ackMaxIntervalMs\x88\x01\x01B\x17\n" +
	"\x15_max_rejected_detailsB\x0e\n" +
	"\f_ack_every_nB\x16\n" +
	"\x14_ack_max_interval_ms\"\xbf\x02\n" +
	"\tIngestAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x04R\brejected\x12B\n" +
	"\x0elogical_status\x18\x03 \x01(\x0e2\x1b.sensor.LogicalIngestStatusR\rlogicalStatus\x12H\n" +
	"\x10technical_status\x18\x04 \x01(\x0e2\x1d.sensor.TechnicalIngestStatusR\x0ftechnicalStatus\x12\x1d\n" +
	"\amessage\x18\x05 \x01(\tH\x00R\amessage\x88\x01\x01\x12A\n" +
	"\x10rejected_details\x18\x06 \x03(\v2\x16.sensor.RejectedDetailR\x0frejectedDetailsB\n" +
	"\n" +
	"\b_message\"\x86\x01\n" +
	"\x0eRejectedDetail\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12)\n" +
	"\x04code\x18\x02 \x01(\x0e2\x15.sensor.RejectionCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\"\x9c\x01\n" +
	"\x19CustomMeasurementsRequest\x12=\n" +
	"\asensors\x18\x01 \x03(\v2#.sensor.CustomMeasurementsForSensorR\asensors\x124\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.sensor.IngestOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\x98\x01\n" +
	"\x1bCustomMeasurementsForSensor\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12=\n" +
	"\fmeasurements\x18\x03 \x03(\v2\x19.sensor.CustomMeasurementR\fmeasurements\"\xe0\x01\n" +
	"\x11CustomMeasurement\x12;\n" +
	"\vmeasured_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"measuredAt\x12=\n" +
	"\x06values\x18\x02 \x03(\v2%.sensor.CustomMeasurement.ValuesEntryR\x06values\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xd4\x02\n" +
	"\x16IngestAccelGyroOptions\x12A\n" +
	"\x0eingest_options\x18\x01 \x01(\v2\x15.sensor.IngestOptionsH\x00R\ringestOptions\x88\x01\x01\x125\n" +
	"\n" +
	"accel_unit\x18\x02 \x01(\x0e2\x11.sensor.AccelUnitH\x01R\taccelUnit\x88\x01\x01\x122\n" +
	"\tgyro_unit\x18\x03 \x01(\x0e2\x10.sensor.GyroUnitH\x02R\bgyroUnit\x88\x01\x01\x12G\n" +
	"\x10temperature_unit\x18\x04 \x01(\x0e2\x17.sensor.TemperatureUnitH\x03R\x0ftemperatureUnit\x88\x01\x01B\x11\n" +
	"\x0f_ingest_optionsB\r\n" +
	"\v_accel_unitB\f\n" +
	"\n" +
	"_gyro_unitB\x13\n" +
	"\x11_temperature_unit\"\xab\x01\n" +
	"\x1cAccelGyroMeasurementsRequest\x12@\n" +
	"\asensors\x18\x01 \x03(\v2&.sensor.AccelGyroMeasurementsForSensorR\asensors\x12=\n" +
	"\aoptions\x18\x02 \x01(\v2\x1e.sensor.IngestAccelGyroOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\x7f\n" +
	"\x1eAccelGyroMeasurementsForSensor\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12@\n" +
	"\fmeasurements\x18\x02 \x03(\v2\x1c.sensor.AccelGyroMeasurementR\fmeasurements\"\x95\x03\n" +
	"\x14AccelGyroMeasurement\x12;\n" +
	"\vmeasured_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"measuredAt\x12\x17\n" +
	"\aaccel_x\x18\x02 \x01(\x01R\x06accelX\x12\x17\n" +
	"\aaccel_y\x18\x03 \x01(\x01R\x06accelY\x12\x17\n" +
	"\aaccel_z\x18\x04 \x01(\x01R\x06accelZ\x12\x15\n" +
	"\x06gyro_x\x18\x05 \x01(\x01R\x05gyroX\x12\x15\n" +
	"\x06gyro_y\x18\x06 \x01(\x01R\x05gyroY\x12\x15\n" +
	"\x06gyro_z\x18\a \x01(\x01R\x05gyroZ\x12%\n" +
	"\vtemperature\x18\b \x01(\x01H\x00R\vtemperature\x88\x01\x01\x12(\n" +
	"\rvibration_rms\x18\t \x01(\x01H\x01R\fvibrationRms\x88\x01\x01\x12*\n" +
	"\x0evibration_peak\x18\n" +
	" \x01(\x01H\x02R\rvibrationPeak\x88\x01\x01B\x0e\n" +
	"\f_temperatureB\x10\n" +
	"\x0e_vibration_rmsB\x11\n" +
	"\x0f_vibration_peak*b\n" +
	"\aAckMode\x12\x18\n" +
	"\x14ACK_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_MODE_FULL\x10\x01\x12\x17\n" +
	"\x13ACK_MODE_STATS_ONLY\x10\x02\x12\x11\n" +
	"\rACK_MODE_NONE\x10\x03*\xa1\x01\n" +
	"\x13LogicalIngestStatus\x12%\n" +
	"!LOGICAL_INGEST_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18LOGICAL_INGEST_STATUS_OK\x10\x01\x12!\n" +
	"\x1dLOGICAL_INGEST_STATUS_PARTIAL\x10\x02\x12\"\n" +
	"\x1eLOGICAL_INGEST_STATUS_REJECTED\x10\x03*\xd0\x02\n" +
	"\x15TechnicalIngestStatus\x12'\n" +
	"#TECHNICAL_INGEST_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTECHNICAL_INGEST_STATUS_OK\x10\x01\x12#\n" +
	"\x1fTECHNICAL_INGEST_STATUS_PENDING\x10\x02\x12)\n" +
	"%TECHNICAL_INGEST_STATUS_RETRYING_MAIN\x10\x03\x12*\n" +
	"&TECHNICAL_INGEST_STATUS_RETRYING_LEVEL\x10\x04\x12*\n" +
	"&TECHNICAL_INGEST_STATUS_LEVEL_FALLBACK\x10\x05\x12!\n" +
	"\x1dTECHNICAL_INGEST_STATUS_ERROR\x10\x06\x12#\n" +
	"\x1fTECHNICAL_INGEST_STATUS_STOPPED\x10\a*W\n" +
	"\rRejectionCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x15\n" +
	"\x11INVALID_SENSOR_ID\x10\x01\x12\"\n" +
	"\x1eUNKNOWN_SENSOR_OR_UNKNOWN_PLAN\x10\x02*:\n" +
	"\x0fTemperatureUnit\x12\v\n" +
	"\aCELSIUS\x10\x00\x12\x0e\n" +
	"\n" +
	"FAHRENHEIT\x10\x01\x12\n" +
	"\n" +
	"\x06KELVIN\x10\x02*\x1c\n" +
	"\tAccelUnit\x12\b\n" +
	"\x04M_S2\x10\x00\x12\x05\n" +
	"\x01G\x10\x01* \n" +
	"\bGyroUnit\x12\t\n" +
	"\x05DEG_S\x10\x00\x12\t\n" +
	"\x05RAD_S\x10\x012\xe9\x02\n" +
	"\rSensorService\x12T\n" +
	"\x18StreamCustomMeasurements\x12!.sensor.CustomMeasurementsRequest\x1a\x11.sensor.IngestAck(\x010\x01\x12O\n" +
	"\x17UnaryCustomMeasurements\x12!.sensor.CustomMeasurementsRequest\x1a\x11.sensor.IngestAck\x12Z\n" +
	"\x1bStreamAccelGyroMeasurements\x12$.sensor.AccelGyroMeasurementsRequest\x1a\x11.sensor.IngestAck(\x010\x01\x12U\n" +
	"\x1aUnaryAccelGyroMeasurements\x12$.sensor.AccelGyroMeasurementsRequest\x1a\x11.sensor.IngestAckB=Z;github.com/brice-74/sensorflow/internal/adapters/grpc/protob\x06proto3"

var (
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescOnce sync.Once
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData []byte
)

func file_back_internal_adapters_grpc_proto_sensor_proto_rawDescGZIP() []byte {
	file_back_internal_adapters_grpc_proto_sensor_proto_rawDescOnce.Do(func() {
		file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc), len(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc)))
	})
	return file_back_internal_adapters_grpc_proto_sensor_proto_rawDescData
}

var file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_back_internal_adapters_grpc_proto_sensor_proto_goTypes = []any{
	(AckMode)(0),                           // 0: sensor.AckMode
	(LogicalIngestStatus)(0),               // 1: sensor.LogicalIngestStatus
	(TechnicalIngestStatus)(0),             // 2: sensor.TechnicalIngestStatus
	(RejectionCode)(0),                     // 3: sensor.RejectionCode
	(TemperatureUnit)(0),                   // 4: sensor.TemperatureUnit
	(AccelUnit)(0),                         // 5: sensor.AccelUnit
	(GyroUnit)(0),                          // 6: sensor.GyroUnit
	(*IngestOptions)(nil),                  // 7: sensor.IngestOptions
	(*IngestAck)(nil),                      // 8: sensor.IngestAck
	(*RejectedDetail)(nil),                 // 9: sensor.RejectedDetail
	(*CustomMeasurementsRequest)(nil),      // 10: sensor.CustomMeasurementsRequest
	(*CustomMeasurementsForSensor)(nil),    // 11: sensor.CustomMeasurementsForSensor
	(*CustomMeasurement)(nil),              // 12: sensor.CustomMeasurement
	(*IngestAccelGyroOptions)(nil),         // 13: sensor.IngestAccelGyroOptions
	(*AccelGyroMeasurementsRequest)(nil),   // 14: sensor.AccelGyroMeasurementsRequest
	(*AccelGyroMeasurementsForSensor)(nil), // 15: sensor.AccelGyroMeasurementsForSensor
	(*AccelGyroMeasurement)(nil),           // 16: sensor.AccelGyroMeasurement
	nil,                                    // 17: sensor.CustomMeasurement.ValuesEntry
	(*timestamppb.Timestamp)(nil),          // 18: google.protobuf.Timestamp
	(*anypb.Any)(nil),                      // 19: google.protobuf.Any
}
var file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs = []int32{
	0,  // 0: sensor.IngestOptions.ack_mode:type_name -> sensor.AckMode
	1,  // 1: sensor.IngestAck.logical_status:type_name -> sensor.LogicalIngestStatus
	2,  // 2: sensor.IngestAck.technical_status:type_name -> sensor.TechnicalIngestStatus
	9,  // 3: sensor.IngestAck.rejected_details:type_name -> sensor.RejectedDetail
	3,  // 4: sensor.RejectedDetail.code:type_name -> sensor.RejectionCode
	11, // 5: sensor.CustomMeasurementsRequest.sensors:type_name -> sensor.CustomMeasurementsForSensor
	7,  // 6: sensor.CustomMeasurementsRequest.options:type_name -> sensor.IngestOptions
	12, // 7: sensor.CustomMeasurementsForSensor.measurements:type_name -> sensor.CustomMeasurement
	18, // 8: sensor.CustomMeasurement.measured_at:type_name -> google.protobuf.Timestamp
	17, // 9: sensor.CustomMeasurement.values:type_name -> sensor.CustomMeasurement.ValuesEntry
	7,  // 10: sensor.IngestAccelGyroOptions.ingest_options:type_name -> sensor.IngestOptions
	5,  // 11: sensor.IngestAccelGyroOptions.accel_unit:type_name -> sensor.AccelUnit
	6,  // 12: sensor.IngestAccelGyroOptions.gyro_unit:type_name -> sensor.GyroUnit
	4,  // 13: sensor.IngestAccelGyroOptions.temperature_unit:type_name -> sensor.TemperatureUnit
	15, // 14: sensor.AccelGyroMeasurementsRequest.sensors:type_name -> sensor.AccelGyroMeasurementsForSensor
	13, // 15: sensor.AccelGyroMeasurementsRequest.options:type_name -> sensor.IngestAccelGyroOptions
	16, // 16: sensor.AccelGyroMeasurementsForSensor.measurements:type_name -> sensor.AccelGyroMeasurement
	18, // 17: sensor.AccelGyroMeasurement.measured_at:type_name -> google.protobuf.Timestamp
	19, // 18: sensor.CustomMeasurement.ValuesEntry.value:type_name -> google.protobuf.Any
	10, // 19: sensor.SensorService.StreamCustomMeasurements:input_type -> sensor.CustomMeasurementsRequest
	10, // 20: sensor.SensorService.UnaryCustomMeasurements:input_type -> sensor.CustomMeasurementsRequest
	14, // 21: sensor.SensorService.StreamAccelGyroMeasurements:input_type -> sensor.AccelGyroMeasurementsRequest
	14, // 22: sensor.SensorService.UnaryAccelGyroMeasurements:input_type -> sensor.AccelGyroMeasurementsRequest
	8,  // 23: sensor.SensorService.StreamCustomMeasurements:output_type -> sensor.IngestAck
	8,  // 24: sensor.SensorService.UnaryCustomMeasurements:output_type -> sensor.IngestAck
	8,  // 25: sensor.SensorService.StreamAccelGyroMeasurements:output_type -> sensor.IngestAck
	8,  // 26: sensor.SensorService.UnaryAccelGyroMeasurements:output_type -> sensor.IngestAck
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_back_internal_adapters_grpc_proto_sensor_proto_init() }
func file_back_internal_adapters_grpc_proto_sensor_proto_init() {
	if File_back_internal_adapters_grpc_proto_sensor_proto != nil {
		return
	}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[0].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[1].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[3].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[6].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[7].OneofWrappers = []any{}
	file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc), len(file_back_internal_adapters_grpc_proto_sensor_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_back_internal_adapters_grpc_proto_sensor_proto_goTypes,
		DependencyIndexes: file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs,
		EnumInfos:         file_back_internal_adapters_grpc_proto_sensor_proto_enumTypes,
		MessageInfos:      file_back_internal_adapters_grpc_proto_sensor_proto_msgTypes,
	}.Build()
	File_back_internal_adapters_grpc_proto_sensor_proto = out.File
	file_back_internal_adapters_grpc_proto_sensor_proto_goTypes = nil
	file_back_internal_adapters_grpc_proto_sensor_proto_depIdxs = nil
}
